version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.1-jdk
    working_directory: ~/assessment
    steps:
      - checkout
      - run:
          name: Login to gcr.io
          command: cat src/main/resources/assesment-devops-3fa87521cee3.json | docker login -u _json_key --password-stdin https://gcr.io/assesment-devops
      - run: mvn clean package -DskipTests
      - run: mvn compile jib:build -Dimage=gcr.io/assesment-devops/assesment:$CIRCLE_BUILD_NUM
  test:
    docker:
      - image: circleci/openjdk:11.0.1-jdk
    working_directory: ~/assessment
    steps:
      - run: mvn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test