apiVersion: v1
kind: Service
metadata:
  name: greetings-assessment-service
  namespace: assessment
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      name: tcp-8080
  selector:
    app: greetings-assessment